version: '3.7'
services:
  db:
    container_name: findnrock-postgres
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data

  adminer:
    container_name: findnrock-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
